### ISSUE TITLE
New skribbl.io update

### ISSUE THREAD

**Issue by ghost** [frienddl-io/frienddl.io-support#34]
## Issue Type

* [x] Question
* [ ] Comment
* [ ] Bug
* [ ] Enhancement
* [ ] Vulnerability

## Short Overview

I'm logging an issue because ...
There is a new skribbl.io update.
## Description

Does this work with the new skribbl.io update automatically by finding an element with the text "Play!" and then clicking on it, for example, or does it have to be manually updated to match the new element IDs and class names?

## Version

**Browser:**

* [ ] N/A
* [x] Chrome
* [ ] Firefox
* [ ] Both

**Version Number:** 2.0.2

**Comment by blakegearin** [comment]
Hey there, hope you're doing well! Thank you for using the extension.

The new skribbl.io update added the ability to invite your friends to public rooms! Simply click on your player icon in the left sidebar during a game to open a modal which has a button to copy an invite URL.

I'll be updating frienddl.io to remove the "find friend" functionality soon since this is now natively supported. The extension will continue to support high score tracking, so I'll reevaluate that functionality to ensure it works with the new update.

**Comment by ghost** [comment]
But what if you don't know which room your friend is in or don't have an invite link to the room they are in?

**Comment by blakegearin** [comment]
I'm not sure I understand. 

The friend finder presupposes A. you know your friend is playing in a public room and B. has sent you their name/username in the game. If B is true, they should be able to send you an invite just as easily as their name.

I guess an alternative situation is trying to find someone you played with before and don't know personally (e.g. missed connection). Is that what you mean?

**Comment by ghost** [comment]
That is what I mean. If you accidentally disconnected without saving the invite link or didn't get their Discord, Instagram, or other social media username before they left, this would be useful.

**Comment by blakegearin** [comment]
I see. I'm not sure how I feel about supporting that for a few reasons.

1. All "friend finders" I've seen for this game are, in effect, a mini DDoS attack. I haven't heard of anyone encountering this with my extension specifically, but I know skribbl.io has banned users for too much activity in a short amount of time. I heard about this before the update when it appeared the game had been abandoned. Which means the bans were likely handed out automatically without human input, and with the reporting options in the new update I imagine banning will only increase. So this extension, and others like it, should be disclaimed as "use at your own risk." Obviously, I also don't want my extension to be abused and used as an attack tool for a game I enjoy, if I can help it.

1. From an ethical perspective, there's always a chance a "missed connection" is one-sided and could devolve into digital stalking. If someone posted a missed connection on Craigslist, the other person could see it, choose to ignore it, and go on with their life without much consequence. On skribbl.io they could "follow you around" unless you change your name. To be fair, I don't have strong feelings about changing my name in the game, but I'm sure others do and would like to keep their name. This is not a new risk, but it was previously offset by helping friends play together.

1. I don't know how common "missed connections" are and there's no way to quantify it. I have seen a couple posts like that on Reddit before. There's also no way of guaranteeing that the player you're trying to find is active when you're searching nor a guarantee that their name is the same. I'd imagine the odds of finding someone would be quite low, all things considered.  It just seems a bit odd to continue devoting half the extension's capabilities (at least that's what it is right now) to such a niche scenario.

1. Almost always, the best way to handle problems is natively inside a game. In this case, this situation could be solved by adding a friend system like Among Us did not too long ago. This would allow people to connect on a more permanent basis without needing to share an email address or social media username in a public room, which can be dangerous. Perhaps you could get in contact with the new developer(s) and ask if they have any plans for a friend system? Looks like their email is contact@skribbl.io. Feel free to CC or BCC me, blakegearin@pm.me.

My hope is that frienddl.io acts as an add-on that helps enhance the game and make it more fun for people who play a lot. So every decision sort of comes down to "Would I use this?" and in this case I think the answer is "No" right now. I'm open to hearing other opinions though.
 
One idea that came to mind while thinking about this is adding the functionality of saving a short list of users recently played against (maybe ~10). That sounds doable and a fun addition if it could keep the total score between you and other players across multiple games to spur a bit of rivalry.

Thoughts?

**Comment by ghost** [comment]
> 1. All "friend finders" I've seen for this game are, in effect, a mini DDoS attack. I haven't heard of anyone encountering this with my extension specifically, but I know skribbl.io has banned users for too much activity in a short amount of time. I heard about this before the update when it appeared the game had been abandoned. Which means the bans were likely handed out automatically without human input, and with the reporting options in the new update I imagine banning will only increase. So this extension, and others like it, should be disclaimed as "use at your own risk." Obviously, I also don't want my extension to be abused and used as an attack tool for a game I enjoy, if I can help it.

It kind of is a mini-DDoS attack in the sense that you are continuing to join and leave random lobbies very quickly in a short amount of time. I was not aware of skribbl.io banning other users, but it seems plausible. I agree that it should be disclaimed as such and I understand that you don't want your extension to be abused. Finding friends is like making a mod to join and leave and join and leave, and many game developers don't like people to modify their game clients. It's like a cat-and-mouse game trying to patch mods and make new mods that bypass those patches.
> 2. From an ethical perspective, there's always a chance a "missed connection" is one-sided and could devolve into digital stalking. If someone posted a missed connection on Craigslist, the other person could see it, choose to ignore it, and go on with their life without much consequence. On skribbl.io they could "follow you around" unless you change your name. To be fair, I don't have strong feelings about changing my name in the game, but I'm sure others do and would like to keep their name. This is not a new risk, but it was previously offset by helping friends play together.

I agree that many people want to keep a consistent name throughout.
> 3. I don't know how common "missed connections" are and there's no way to quantify it. I have seen a couple posts like that on Reddit before. There's also no way of guaranteeing that the player you're trying to find is active when you're searching nor a guarantee that their name is the same. I'd imagine the odds of finding someone would be quite low, all things considered.  It just seems a bit odd to continue devoting half the extension's capabilities (at least that's what it is right now) to such a niche scenario.

There is also always a risk of finding someone else who has copied the same name (either by coincidentally coming up with the same name or on purpose) and/or the same avatar in a public lobby. I agree that there's no guarantee that the player you're trying to find is active or that their name is the same. Posts on the r/skribbl subreddit about finding players are categorized by the ":create: User Search" flair.
> 4. Almost always, the best way to handle problems is natively inside a game. In this case, this situation could be solved by adding a friend system like Among Us did not too long ago. This would allow people to connect on a more permanent basis without needing to share an email address or social media username in a public room, which can be dangerous. Perhaps you could get in contact with the new developer(s) and ask if they have any plans for a friend system? Looks like their email is [contact@skribbl.io](mailto:contact@skribbl.io). Feel free to CC or BCC me, [blakegearin@pm.me](mailto:blakegearin@pm.me).

It can be dangerous to share an email address or social media username in a public room. It's the same developer, Mel. The display name "mel" was already used in the Twitter account of the game's developer, ticedev, which was linked from the game if you look at past skribbl.io on the Wayback Machine. More people got added to the credits, though; before then, the only thing in the credits was the sound used for the ticking clock. That is the correct email address, but the developer, unfortunately, currently does not ever respond to emails sent to [contact@skribbl.io](mailto:contact@skribbl.io). I heard from someone who apparently knew the game dev, pog, that Mel doesn't want random people to be contacting him or like it when random people contact him anyway.
> My hope is that frienddl.io acts as an add-on that helps enhance the game and make it more fun for people who play a lot. So every decision sort of comes down to "Would I use this?" and in this case I think the answer is "No" right now. I'm open to hearing other opinions though.

Fair enough.
> One idea that came to mind while thinking about this is adding the functionality of saving a short list of users recently played against (maybe ~10). That sounds doable and a fun addition if it could keep the total score between you and other players across multiple games to spur a bit of rivalry.
> 
> Thoughts?

I'm not sure, but it is possible to implement; though if there's a limit as to how many users listed are stored, someone might accidentally be knocked off the list and their total score recorded may reset back to zero.

Update: I just now realized that Skribbl Typo offers the same functionality lol.
